services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - appnet

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
